name: Java CI with Maven

on:
  push:
    branches:
      - master    # Trigger the workflow on push to the "main" branch
  pull_request:
    branches:
      - master    # Trigger the workflow on pull request to the "main" branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest    # Use the latest Ubuntu runner on GitHub Actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4    # Check out the code in the repository

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'   # You can change this version based on your project needs
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository   # Cache the local Maven repository to speed up builds
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}   # Use the `pom.xml` hash for cache key
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests   # Run Maven clean and install without running tests

      - name: Run tests with Maven
        run: mvn test   # Run the actual tests

      - name: Upload test results (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/testng-results.xml   # Assuming you use TestNG
          compression-level: 0 # no compression
